name: E-commerce React App

env:
  VERCEL_ORG_ID:${{secrets.VERECEL_ORD_ID}}
  VERECEL_PROJECT_ID:${{secrets.VERCEL_PROJECT_ID}}
on:
  push:
    branches:
      -main
      -master
  pull_request:
    branches:
      -main
      -master

jobs:
  Deploy-Production:
    runs-on:ubuntu-latest

    steps:
      -uses:actions/checkout@v2
      -name: Install Vercel CLI
       run:npm install --global vercel@latest
      -name: Pull Vercel Environment Information
       run: vercell pull --yes --environment=production --token=${{secrects.VERCEL_TOKEN}}
      -name: Build Project Artifcats
       run: vercel build --prod --token=${{secrets.VERCEL_TOKEN}}
      -name: Deploy Project Artifcats to Vercel
       run: vercel deploy --prebuilt --prod --token=${{secrets.VERCEL_TOKEN}}
      
